### ISSUE TITLE
Feedback - Da Github keine Feedback Option hat lol

### ISSUE THREAD

**Issue by TheMelone2** [SLH335/MCG-App#13]
So erstmal Hey an das Entwickler Team!

Ich hab mir die App jetztmal angeschaut und hab ein kleines Feedback vorbereitet:
_wer hätte es nachdem Titel gedacht_

Das Feedback bezieht sich auf folgende Bereiche und soll keineswegs abwertend klingen, da die App in einer sehr frühen Alpha ist (ich weiß wie anstrengend sowas ist...):
- Hauptsächlich auf das UX Design

Nun zum Feedback, fangen wir an!

**Whitemode:**
Das Design im Whitemode ist mit dem typischen Grün der Schule, gut getroffen! Jedoch wirkt der Teil unter dem App Name in der Navigationbar, etwas naja leer.
Vielleicht wäre da das MCG-Logo ganz passend 🤔

**App Icon:**
Auch wenn das jetzt meine persönliche Meinung ist, es sehe etwas moderner aus, wenn man das App Icon nicht so kastig (durch den weißen Background macht), sondern es entwerder rund "abschneidet" bzw. den Background ganz entfernt.

**Raumplan:**
Der Raumplan ist eine super Idee, jedoch gibt es für mich dort ein paar "nervige" Sachen.
Der Raumplan würde irgendwie etwas besser aussehen, wenn er Zentral in der Mitte des Bildschirmes wäre und nicht unter dem App Namen / Headline.
Auch das der Bildschirm, wenn man auf einen Raum klickt, dunkler wird, nervt ein bisschen.

**Lehrerliste:**
Die Lehrerliste ist wirklich super!
Dort wäre mein einziger Verbesserungswunsch, dass man die Email's der Lehrer*innen per einem Klick auf die Email ins Clipboard kopieren könnte.

**Darkmode:**
Natürlich gibt es zum wichtigsten Feature, dem Darkmode, auch etwas zu schreiben ✍️😀
Der Darkmode ist extreeem geil, vorallem nachts (also jetzt als ich das Feedback schreibe 😇). Leider sehen die Farben etwas eintönig und "lahm" aus.
Vielleicht könnte der Header in einem Dunkelgrün sein, ach und das gleiche wie bei der Navigationbar beim Whitemode...
Außerdem wäre es schön, wenn die Darkmode Einstellung einen Lokalen Toggle bekommt, damit sie permanent entweder auf true oder false ist.
Da man sonst bei jedem restart der App, es wieder umstellen muss.

**Trotzdem nochmal, danke für die App**

(Mich kann man, falls ihr das wollt, über Schul.cloud [_Jan Luca Heise_] erreichen, oder über Discord: _TheMelone2#9991_ 😅)

Beste Grüße von Jan Luca aus der 9c!

**Comment by TheMelone2** [comment]
Anhang: Außerdem wäre für den "Lehrer"-Tab eine Filter Funktion, nach Fach cool ;)

**Comment by SLH335** [comment]
Moin @TheMelone2,

vielen Dank für dein tolles Feedback! Es freut mich sehr, dass dir die App gefällt und generell Interesse daran besteht, dass ich daran weiterarbeite. Dann werde ich das auch auf jeden Fall tun!

> Whitemode:
Das Design im Whitemode ist mit dem typischen Grün der Schule, gut getroffen! Jedoch wirkt der Teil unter dem App Name in der Navigationbar, etwas naja leer.
Vielleicht wäre da das MCG-Logo ganz passend

Ja, das stimmt. Die App wird in Zukunft User Accounts für Schüler bekommen, um den Stundenplan, Noten usw. anzeigen zu können. Dann werde ich im "Drawer Header" (so heißt das Teil:smile:) den Namen, das Profilbild und die E-Mail des Users anzeigen. Bis das kommt, werde ich aber auf deinen Vorschlag hin das MCG-Logo dort einbauen.

> App Icon:
Auch wenn das jetzt meine persönliche Meinung ist, es sehe etwas moderner aus, wenn man das App Icon nicht so kastig (durch den weißen Background macht), sondern es entwerder rund "abschneidet" bzw. den Background ganz entfernt.

Ich weiß nicht so richtig, warum Android das Icon nicht rund abgeschnitten hat, aber hoffentlich ist es beim nächsten Release behoben. Das Schullogo macht sich generell nicht so gut für ein App-Icon, weil das Atom so dünn ist. Vielleicht können wir ja ein Logo eigens für die App designen. Ich habe schon ein paar Ideen.

> Raumplan:
Der Raumplan ist eine super Idee, jedoch gibt es für mich dort ein paar "nervige" Sachen.
Der Raumplan würde irgendwie etwas besser aussehen, wenn er Zentral in der Mitte des Bildschirmes wäre und nicht unter dem App Namen / Headline.
Auch das der Bildschirm, wenn man auf einen Raum klickt, dunkler wird, nervt ein bisschen.

Es ist auf jeden Fall so gedacht, dass der Raumplan mittig ist und sich auch dynamisch an die Bildschirmgröße anpasst, leider hatte ich vor der Präsentation keine Zeit mehr, das Problem zu beheben. Ich werde zum nächsten Release generell die Logik des Raumplans überarbeiten. Dann sollte er mittig sein, die Raumnummern sollten alle in ihre Räume passen und der Bildschirm sollte beim Anzeigen der Details normal hell bleiben.

> Lehrerliste:
Die Lehrerliste ist wirklich super!
Dort wäre mein einziger Verbesserungswunsch, dass man die Email's der Lehrer*innen per einem Klick auf die Email ins Clipboard kopieren könnte.

Das ist eine sehr gute Idee. Entweder wir machen das so, oder es wird ein mailto-Link, wo sich beim Klick direkt das Mailprogramm, adressiert an den Lehrer, öffnet.

> Darkmode:
Natürlich gibt es zum wichtigsten Feature, dem Darkmode, auch etwas zu schreiben
Der Darkmode ist extreeem geil, vorallem nachts (also jetzt als ich das Feedback schreibe). Leider sehen die Farben etwas eintönig und "lahm" aus.
Vielleicht könnte der Header in einem Dunkelgrün sein, ach und das gleiche wie bei der Navigationbar beim Whitemode...
Außerdem wäre es schön, wenn die Darkmode Einstellung einen Lokalen Toggle bekommt, damit sie permanent entweder auf true oder false ist.
Da man sonst bei jedem restart der App, es wieder umstellen muss.

Tatsächlich hatte ich bis jetzt keine Zeit, viel Aufwand in den Dark Mode zu stecken, deshalb ist er gerade einfach nur in den Standardfarben :joy: Das grüne Design wird aber definitiv noch in beiden Farbschemas eingebaut.

Nochmal vielen Dank für das Feedback! Die App wird auf jeden Fall weiterentwickelt. Perfekt, dass du Discord erwähnt hast, ich habe nämlich dort auch einen MCG-Schulserver erstellt, zu dem ich dich gerne einlade. Du solltest eine Freundschaftsanfrage von mir bekommen haben. Ich schreibe den Link auch mal in die Discord-Beschreibung.

Liebe Grüße
Sven Luca Hafemann, 11. Klasse
